--create music album table--
CREATE TABLE MUSIC_ALBUM_(
    ID INTEGER PRIMARY KEY,
    ON_SPOTIFY BOOLEAN,
    ARCHIVED BOOLEAN
    PUBLISH_DATE DATE
)

--Create Genre table--
CREATE TABLE IF NOT EXISTS GENRE (
    ID INTEGER PRIMARY KEY,
    NAME CHAR(32) NOT NULL,
)