--create music album table--
CREATE TABLE MUSIC_ALBUM(
    ID INTEGER PRIMARY KEY,
    ON_SPOTIFY BOOLEAN,
    ARCHIVED BOOLEAN,
    PUBLISH_DATE DATE,
    GENRE VARCHAR(100) REFERENCES GENRE(NAME),
    AUTHOR VARCHAR(100) REFERENCES authors(first_name),
    LABEL VARCHAR(100) REFERENCES labels(TITLE),
)

--Create Genre table--
CREATE TABLE IF NOT EXISTS GENRE(
    ID INTEGER,
    NAME CHAR(32) NOT NULL,
    ITEMS INT REFERENCES (books, MUSIC_ALBUM, games),
    PRIMARY KEY(ID, ITEMS)
)